version: "3.8"

services:
  marketcap-api:
    build: .
    container_name: marketcap-api
    ports:
      - "5000:5000"
    restart: always
    networks:
      - n8n-net

networks:
  n8n-net:
    external: true
